platform :ios, '10.0'

target 'JJLISO8601DateFormatterApp' do
  pod 'JJLISO8601DateFormatter', :path => '../'
end

target 'JJLISO8601DateFormatterTesting' do
  pod 'JJLISO8601DateFormatter', :path => '../'
  pod 'OCMock'
end
